---
vms:
- name: master
  hostname: master
  box: ubuntu-server-12042-x64-vbox4210-nocm
  roles:
  - pe-puppet-master
- name: deployit
  hostname: deployit.local
  box: centos-64-x64-vbox4210-nocm
  roles:
  - pe-puppet-agent
