---
vms:
- name: master
  hostname: master
  box: ubuntu-server-12042-x64-vbox4210-nocm
  roles:
  - pe-puppet-master
- name: deployit
  hostname: deployit.local
  box: centos-64-x64-vbox4210-nocm
  roles:
  - pe-puppet-agent-dev
- name: test
  hostname: test.local
  box: centos-64-x64-vbox4210-nocm
  roles:
  - pe-puppet-agent-dev
- name: wildfly1
  hostname: wildfly1.local
  box: centos-64-x64-vbox4210-nocm
  roles:
  - pe-puppet-agent-dev
- name: xldeploy
  hostname: xldeploy.local
  box: centos-64-x64-vbox4210-nocm
  roles:
  - pe-puppet-agent-dev
- name: wildflyxl
  hostname: wildflyxl.local
  box: centos-64-x64-vbox4210-nocm
  roles:
  - pe-puppet-agent-dev
- name: gitlab1
  hostname: gitlab1.local
  box: centos-64-x64-vbox4210-nocm
  roles:
  - pe-puppet-agent-dev
- name: haproxy1
  hostname: haproxy1.local
  box: centos-64-x64-vbox4210-nocm
  roles:
  - pe-puppet-agent-dev
- name: consul1
  hostname: consul1.local
  box: centos-64-x64-vbox4210-nocm
  roles:
  - pe-puppet-agent-dev
